import nft from "../../../icons/nft.jpg";
import nft2 from "../../../icons/nft-book.jpg";
export const nftData = [
  {
    statecard: "liked",
    value: "ArtWork",
    img: nft,
    name: "Liquid Wave",
    time: "3h 1m 50s",
    bid: "0.05 ETH",
    currentBid: "0.15 ETH",
  },
  {
    statecard: "liked",
    value: "Book",
    img: nft2,
    name: "Liquid Wave",
    time: "3h 1m 50s",
    bid: "0.05 ETH",
    currentBid: "0.15 ETH",
  },
  {
    statecard: "liked",
    value: "ArtWork",
    img: nft,
    name: "Liquid Wave",
    time: "3h 1m 50s",
    bid: "0.05 ETH",
    currentBid: "0.15 ETH",
  },
  {
    statecard: "liked",
    value: "Book",
    img: nft2,
    name: "Liquid Wave",
    time: "3h 1m 50s",
    bid: "0.05 ETH",
    currentBid: "0.15 ETH",
  },
  {
    statecard: "liked",
    value: "ArtWork",
    img: nft,
    name: "Liquid Wave",
    time: "3h 1m 50s",
    bid: "0.05 ETH",
    currentBid: "0.15 ETH",
  },
  {
    statecard: "liked",
    value: "Book",
    img: nft2,
    name: "Liquid Wave",
    time: "3h 1m 50s",
    bid: "0.05 ETH",
    currentBid: "0.15 ETH",
  },
  {
    statecard: "liked",
    value: "ArtWork",
    img: nft,
    name: "Liquid Wave",
    time: "3h 1m 50s",
    bid: "0.05 ETH",
    currentBid: "0.15 ETH",
  },
  {
    statecard: "liked",
    value: "Book",
    img: nft2,
    name: "Liquid Wave",
    time: "3h 1m 50s",
    bid: "0.05 ETH",
    currentBid: "0.15 ETH",
  },
];
